import type { Plan } from '$lib/features/plans/plans.model';

/**
 * DATA CONTOH Master Paket — hanya dimuat saat `dev` tanpa backend (FE-04 D2), simpan disimulasikan lokal.
 * Isi CERMIN seeder backend (`cmd/lmsctl/seed_plans.go`, 10 paket referensi), bukan aturan bisnis.
 */
export const plansFixture: Plan[] = [
	{
		code: 'SCH_BASIC',
		name: 'Basic',
		tenant_type_code: 'school',
		status: 'active',
		badge: '',
		description: 'LMS inti untuk kelas dan tugas.',
		pricing_model: 'seat',
		price_idr: 5000,
		tax_mode: 'excl',
		free_months: 2,
		min_seats: 50,
		max_seats: 2000,
		max_teachers: null,
		storage_gb: 50,
		email_invites_per_month: 500,
		max_participants_per_session: null,
		session_minutes: null,
		max_parallel_sessions: null,
		session_gap_minutes: null,
		proctoring: 'none',
		allow_topup: true,
		tiers: [],
		trial_enabled: true,
		trial_length: 5,
		trial_unit: 'business_day',
		trial_manual_approval: true,
		trial_max_students: 100,
		trial_one_per_npsn: true,
		features: ['auto_graded_exam', 'lms', 'question_bank', 'report_attendance'],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'SCH_STANDARD',
		name: 'Standard',
		tenant_type_code: 'school',
		status: 'active',
		badge: 'Paling dipilih',
		description: 'Ditambah portal orang tua dan analitik.',
		pricing_model: 'seat',
		price_idr: 6000,
		tax_mode: 'excl',
		free_months: 2,
		min_seats: 50,
		max_seats: 2000,
		max_teachers: null,
		storage_gb: 100,
		email_invites_per_month: 500,
		max_participants_per_session: null,
		session_minutes: null,
		max_parallel_sessions: null,
		session_gap_minutes: null,
		proctoring: 'none',
		allow_topup: true,
		tiers: [],
		trial_enabled: true,
		trial_length: 5,
		trial_unit: 'business_day',
		trial_manual_approval: true,
		trial_max_students: 100,
		trial_one_per_npsn: true,
		features: [
			'auto_graded_exam',
			'guardian_portal',
			'item_analysis',
			'lms',
			'principal_dashboard',
			'question_bank',
			'report_attendance'
		],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'SCH_PREMIUM',
		name: 'Premium',
		tenant_type_code: 'school',
		status: 'active',
		badge: '',
		description: 'Asisten AI dan identitas sendiri.',
		pricing_model: 'seat',
		price_idr: 7500,
		tax_mode: 'excl',
		free_months: 2,
		min_seats: 50,
		max_seats: 2000,
		max_teachers: null,
		storage_gb: 250,
		email_invites_per_month: 500,
		max_participants_per_session: null,
		session_minutes: null,
		max_parallel_sessions: null,
		session_gap_minutes: null,
		proctoring: 'none',
		allow_topup: true,
		tiers: [],
		trial_enabled: true,
		trial_length: 5,
		trial_unit: 'business_day',
		trial_manual_approval: true,
		trial_max_students: 100,
		trial_one_per_npsn: true,
		features: [
			'ai_assistant',
			'auto_graded_exam',
			'guardian_portal',
			'item_analysis',
			'lms',
			'principal_dashboard',
			'question_bank',
			'report_attendance',
			'whatsapp_notification',
			'white_label'
		],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'SCH_YAYASAN',
		name: 'Yayasan',
		tenant_type_code: 'school',
		status: 'draft',
		badge: '',
		description: 'Untuk yayasan dengan beberapa sekolah.',
		pricing_model: 'seat',
		price_idr: 5500,
		tax_mode: 'excl',
		free_months: 2,
		min_seats: 1000,
		max_seats: 20000,
		max_teachers: null,
		storage_gb: 50,
		email_invites_per_month: 500,
		max_participants_per_session: null,
		session_minutes: null,
		max_parallel_sessions: null,
		session_gap_minutes: null,
		proctoring: 'none',
		allow_topup: true,
		tiers: [],
		trial_enabled: true,
		trial_length: 5,
		trial_unit: 'business_day',
		trial_manual_approval: true,
		trial_max_students: 100,
		trial_one_per_npsn: true,
		features: [
			'auto_graded_exam',
			'guardian_portal',
			'item_analysis',
			'lms',
			'principal_dashboard',
			'question_bank',
			'report_attendance',
			'whatsapp_notification'
		],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'TCH_SOLO',
		name: 'Solo',
		tenant_type_code: 'personal',
		status: 'active',
		badge: '',
		description: 'Hingga 30 murid.',
		pricing_model: 'flat',
		price_idr: 49000,
		tax_mode: 'excl',
		free_months: 2,
		min_seats: null,
		max_seats: 30,
		max_teachers: null,
		storage_gb: 10,
		email_invites_per_month: 100,
		max_participants_per_session: null,
		session_minutes: null,
		max_parallel_sessions: null,
		session_gap_minutes: null,
		proctoring: 'none',
		allow_topup: true,
		tiers: [],
		trial_enabled: true,
		trial_length: 24,
		trial_unit: 'hour',
		trial_manual_approval: false,
		trial_max_students: 20,
		trial_one_per_npsn: false,
		features: ['auto_graded_exam', 'lms', 'question_bank'],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'TCH_PLUS',
		name: 'Plus',
		tenant_type_code: 'personal',
		status: 'active',
		badge: 'Paling dipilih',
		description: 'Hingga 100 murid.',
		pricing_model: 'flat',
		price_idr: 99000,
		tax_mode: 'excl',
		free_months: 2,
		min_seats: null,
		max_seats: 100,
		max_teachers: null,
		storage_gb: 25,
		email_invites_per_month: 300,
		max_participants_per_session: null,
		session_minutes: null,
		max_parallel_sessions: null,
		session_gap_minutes: null,
		proctoring: 'none',
		allow_topup: true,
		tiers: [],
		trial_enabled: true,
		trial_length: 24,
		trial_unit: 'hour',
		trial_manual_approval: false,
		trial_max_students: 20,
		trial_one_per_npsn: false,
		features: ['auto_graded_exam', 'guardian_portal', 'item_analysis', 'lms', 'question_bank'],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'TCH_PRO',
		name: 'Pro',
		tenant_type_code: 'personal',
		status: 'active',
		badge: '',
		description: 'Hingga 250 murid.',
		pricing_model: 'flat',
		price_idr: 149000,
		tax_mode: 'excl',
		free_months: 2,
		min_seats: null,
		max_seats: 250,
		max_teachers: null,
		storage_gb: 50,
		email_invites_per_month: 600,
		max_participants_per_session: null,
		session_minutes: null,
		max_parallel_sessions: null,
		session_gap_minutes: null,
		proctoring: 'none',
		allow_topup: true,
		tiers: [],
		trial_enabled: true,
		trial_length: 24,
		trial_unit: 'hour',
		trial_manual_approval: false,
		trial_max_students: 20,
		trial_one_per_npsn: false,
		features: [
			'ai_assistant',
			'auto_graded_exam',
			'custom_domain',
			'guardian_portal',
			'item_analysis',
			'lms',
			'question_bank'
		],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'EVT_REG',
		name: 'Ujian Reguler',
		tenant_type_code: 'event',
		status: 'active',
		badge: '',
		description: 'Hingga 300 peserta per sesi.',
		pricing_model: 'package',
		price_idr: 750000,
		tax_mode: 'excl',
		free_months: 0,
		min_seats: null,
		max_seats: null,
		max_teachers: null,
		storage_gb: null,
		email_invites_per_month: null,
		max_participants_per_session: 300,
		session_minutes: 120,
		max_parallel_sessions: 2,
		session_gap_minutes: 15,
		proctoring: 'none',
		allow_topup: true,
		tiers: [
			{
				min_sessions: 5,
				price_idr: 650000
			},
			{
				min_sessions: 10,
				price_idr: 600000
			}
		],
		trial_enabled: false,
		trial_length: null,
		trial_unit: null,
		trial_manual_approval: false,
		trial_max_students: null,
		trial_one_per_npsn: false,
		features: ['auto_graded_exam', 'participant_certificate', 'question_bank'],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'EVT_PROC',
		name: 'Ujian Terawasi',
		tenant_type_code: 'event',
		status: 'active',
		badge: 'Paling dipilih',
		description: 'Dengan rekaman kamera dan layar.',
		pricing_model: 'package',
		price_idr: 950000,
		tax_mode: 'excl',
		free_months: 0,
		min_seats: null,
		max_seats: null,
		max_teachers: null,
		storage_gb: null,
		email_invites_per_month: null,
		max_participants_per_session: 300,
		session_minutes: 120,
		max_parallel_sessions: 3,
		session_gap_minutes: 15,
		proctoring: 'camscreen',
		allow_topup: true,
		tiers: [
			{
				min_sessions: 5,
				price_idr: 850000
			},
			{
				min_sessions: 10,
				price_idr: 800000
			}
		],
		trial_enabled: false,
		trial_length: null,
		trial_unit: null,
		trial_manual_approval: false,
		trial_max_students: null,
		trial_one_per_npsn: false,
		features: ['auto_graded_exam', 'item_analysis', 'participant_certificate', 'question_bank'],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	},
	{
		code: 'EVT_TO180',
		name: 'Try Out 180',
		tenant_type_code: 'event',
		status: 'draft',
		badge: '',
		description: 'Sesi panjang untuk try out.',
		pricing_model: 'package',
		price_idr: 1100000,
		tax_mode: 'excl',
		free_months: 0,
		min_seats: null,
		max_seats: null,
		max_teachers: null,
		storage_gb: null,
		email_invites_per_month: null,
		max_participants_per_session: 1000,
		session_minutes: 180,
		max_parallel_sessions: 2,
		session_gap_minutes: 30,
		proctoring: 'cam',
		allow_topup: true,
		tiers: [
			{
				min_sessions: 5,
				price_idr: 990000
			}
		],
		trial_enabled: false,
		trial_length: null,
		trial_unit: null,
		trial_manual_approval: false,
		trial_max_students: null,
		trial_one_per_npsn: false,
		features: ['auto_graded_exam', 'item_analysis', 'participant_certificate', 'question_bank'],
		subscription_count: 0,
		updated_at: '2026-10-05T00:00:00.000Z'
	}
];
